### ISSUE TITLE
Create version for all platforms

### ISSUE THREAD

**Issue by andreisss** [wagga40/Zircolite#41]
For old linux version there is an issue, would be good to have -lin-musl - one.
Issue type: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by ./zircolite_lin)

**Comment by wagga40** [comment]
Thanks for the issue.
You're right. Since building the releases is not fully automated, I don't have the right build environnement to do that. I was working on it. 

As a temporary workaround, may be pyinstaller can work (check [here](https://github.com/wagga40/Zircolite/blob/master/docs/Advanced.md#packaging-zircolite))

**Comment by wagga40** [comment]
Still working on it, check this example on ARM 64bits : 

<img width="759" alt="Screenshot 2022-11-12 at 11 40 58" src="https://user-images.githubusercontent.com/6437862/201470441-c528c90a-e424-4efe-a1bd-da5741a633d5.png">

**Comment by wagga40** [comment]
Hi, I think it is done... there are even ARM64/AARCH64 versions : check [here](https://github.com/wagga40/Zircolite/releases/tag/2.9.7).

**Comment by andreisss** [comment]
Hi, thanks for your work.
