### ISSUE TITLE
Ingest XML events

### ISSUE THREAD

**Issue by Blaapje** [wagga40/Zircolite#52]
How much work would it take to ingest xml data rather than evtx files? 

The XML data is generated by: [https://github.com/williballenthin/EVTXtract](https://github.com/williballenthin/EVTXtract). The tools recovers (partial) xml records from corrupted partitions. 

Could you indicate if this is feasible and give some pointers towards ingesting xml data? I'd be happy to submit a PR if I get this to work.

**Comment by wagga40** [comment]
As a quick response I can say that Zircolite already handles XML formatted logs because it is the native format of sysmon for linux logs (`--sysmon4linux`).
 I haven’t tested with logs coming from EVTXtract.

**Comment by wagga40** [comment]
Ok forgot what I've said, I took a look to the output of EVTXtract and it is a little bit more difficult than that...

**Comment by Blaapje** [comment]
It's rather interesting that both EVTXtract and evtx_dump are both maintained by williballenthin. I will see if I can get this working.

**Comment by wagga40** [comment]
In `Zircolite` everything (EVTX, Auditd, Sysmon For Linux) is converted to JSON lines format. 
These operations are handled by the [evtxExtractor](https://github.com/wagga40/Zircolite/blob/8f39b6bd447b2dcc3aaecbd433b91c4d77873b64/zircolite_dev.py#L668) class. For each log file the [Logs2JSON](https://github.com/wagga40/Zircolite/blob/8f39b6bd447b2dcc3aaecbd433b91c4d77873b64/zircolite_dev.py#L798) function is called for each line in the log file to convert it to JSON.

Since the XML output of `EVTXtract` is not in the "1 event per line" format, the first thing is to handle this. The easiest way to to it would be to modify EVTXtract (check [here](https://github.com/williballenthin/EVTXtract/blob/0ed9ff341ec7d344d7a5af7e5d1f8fbbc5949e89/evtxtract/main.py#L14)) (but I guess that's not what you want to do) and use XML to JSON conversion logic like the one used [here](https://github.com/wagga40/Zircolite/blob/8f39b6bd447b2dcc3aaecbd433b91c4d77873b64/zircolite_dev.py#L754).

If you have samples I can help...

**Comment by Blaapje** [comment]
I've made a small sample available here: https://gist.github.com/Blaapje/23e378748db737960a90c723c2dc8676

**Comment by wagga40** [comment]
Thanks, I will try this week end.

**Comment by wagga40** [comment]
Hi @Blaapje, worked on it ! I currently only handle events beginning with `<event>` and not the other ones (i.e `<record>`) since they don’t contains the fields that allows to apply sigma on them. I will push something today.

**Comment by wagga40** [comment]
You can try with this branch : https://github.com/wagga40/Zircolite/tree/evtxtract
