### ISSUE TITLE
Parsing EVTX folder with Windows 10 Binaries (embedded) is NOT working

### ISSUE THREAD

**Issue by evild3ad** [wagga40/Zircolite#8]
I tried Zircolite v2.1.0 (zircolite_win10_nuitka_embedded.exe). Zircolite vs. an EVTX files works smoothly, but parsing an EVTX folder with the dropped evtx_dump.exe stops latest after 5% (17 EVTX files). I tried different terminals. 

I gave also zircolite_win10_embedded.exe a chance...same issue. Please have a look. Thank you!

**Comment by evild3ad** [comment]
I tried Zircolite from source....same issue. evtx_dump.exe hangs after parsing some EVTX files.

**Comment by wagga40** [comment]
Hello, 

I've encountered the problem once or two, the issue comes from [evtx_dump](https://github.com/omerbenamram/evtx/) which I'm relying on. In fact, evtx_dump is totally blocking sometimes on certain EVTX files (Issue [here](https://github.com/omerbenamram/evtx/issues)). So, if you are using it on a folder (which is my usual use case), there are multiples options : 
- **you can try with the '--no-external' argument which uses _evtx_dump_ as a lib (with python bindings) and no external binaries. But it is quite slower...**
- you can kill the evtx_dump process that is blocking (with process hacker it's easier) and it will skip the blocking EVTX file.
- you can identify and remove the EVTX which is the one blocking (the 🙈 solution)

**If** you can share your blocking EVTX file, I would be happy to post an issue in [evtx_dump](https://github.com/omerbenamram/evtx/) repo.

**Comment by evild3ad** [comment]
I switched to my MacBook...everything is working here. :-)

The EVTX files are from a Windows Server 2008 R2 (154,9 MB, 353 EVTX files), but I cannot share it (customer data). 
I will go on playing with Zircolite the next days. Maybe I can use EvtxECmd on Windows (JSON output) instead of evtx_dump. 

I used Mini GUI to visualize the detections. RDP Brute Forcing has a wrong title and description (WMI Event Subscription).

![2021-08-15_09-59-01](https://user-images.githubusercontent.com/8110531/129474368-3d72a08a-6565-436d-91c5-201ab8c6192f.png)

Are you planning to add MITRE Techniques?

Thank you! Very nice and promising tool!

**Comment by evild3ad** [comment]
detected_events.json seems to be correct.

**Comment by wagga40** [comment]
> I switched to my MacBook...everything is working here. :-)

Yes, I should have said that I encountered this problem only when running evtx_dump on Windows 😅. If you can test with the '--no-external' option and confirm it works to allow me to add a "known issues" topic in the docs, it would be quite helpful.

> Maybe I can use EvtxECmd on Windows (JSON output) instead of evtx_dump

I use **evtx_dump** because it is insanely fast... But you are right, may be I will test some alternatives.

> I used Mini GUI to visualize the detections. RDP Brute Forcing has a wrong title and description (WMI Event Subscription).

Weird, could you elaborate ?

> Are you planning to add MITRE Techniques?

In the Mini-GUI you mean ? why not, I was expecting feedback before working more on it (like you have just done). Because, to be honest, I work with big datasets and I prefer to forward my detected events to a Splunk instance and work from there.

> Thank you! Very nice and promising tool!

Thanks to you for using it ! Don't hesitate to spread the word.
FYI, the next version will be released soon (finished but still testing), changes : 
- since I have made some changes in Sigma repo, **Zircolite** will be able to convert SIGMA rules on the fly directly allowing to directly use SIGMA Rules instead of pre-generated rulesets (but their will continue to be the better and faster way)
- for the same reason as above, you don't need to use genRules to generate rulesets anymore and can generate rulesets directly from the officiel sigmac tool

**Comment by evild3ad** [comment]
I tested using --noexternal on Windows (zircolite_win10_nuitka_embedded.exe and zircolite_win10_embedded.exe) and it worked! :-)

Yes, next to the tactics if would be nice to filter with techniques in the Mini-GUI too (more granular).

May you add the detected events (seen on the screen) to zircolite.log? Would be nice.

Cheers!

**Comment by evild3ad** [comment]
The RDP Brute Forcing attempts are also categorized as "Persistence" --> "WMI Event Subscription" on Windows (Mini-GUI). 

Microsoft-Windows-TerminalServices-LocalSessionManager/Operational.evtx
Event ID: 21
LogonType: 3
Failure Reason: Unknown user name or bad password.
Status: 0xC000006D

Should be categorized as:
Tactic: Credential Access
Technique: T1110 --> T1110.001
https://attack.mitre.org/techniques/T1110/001/

**Comment by wagga40** [comment]
> The RDP Brute Forcing attempts are also categorized as "Persistence" --> "WMI Event Subscription" on Windows (Mini-GUI).

Ah ok 👌

This is because this is a false positive. The rule "WMI Event Subscription" that detects your events is converted to Zircolite format (SQLite) with the default "generic" [config file](https://github.com/wagga40/Zircolite/blob/master/tools/genRules/config/generic.yml). 
In fact, the rule is converted to : `SELECT * FROM logs WHERE EventID IN ("19", "20", "21")` (yes... 😩) which will match pretty much against anything where there is event with eventID 19, 20 or 21. 
This is because the [original rule](https://github.com/SigmaHQ/sigma/blob/1ff5e226ad8bed34916c16ccc77ba281ca3203ae/rules/windows/wmi_event/sysmon_wmi_event_subscription.yml) was originally written for Sysmon event only (hence the hardcoded eventID).

Event if I strongly recommend to use your own ruleset, I think I will remove this rule in default ruleset in the next release.

As for the RDP brute force detection an other rule should detect it.

> Why the strange file name when using --exportforzircogui?

Since the embedded versions are automatically generated from the [genEmbed](https://github.com/wagga40/Zircolite/tree/master/tools/genEmbed) tool, I do not do exception for this template.

You can use the "--package" option introduced in the last version to automatically generate a new Mini-Gui package.
