### ISSUE TITLE
Some problems when using audit.log

### ISSUE THREAD

**Issue by hoanga2dtk68** [wagga40/Zircolite#86]
![image](https://github.com/user-attachments/assets/43a8c621-79f8-40d4-bd9b-d6038fcfbb6d)
![image](https://github.com/user-attachments/assets/f1d48cd4-6d51-47c1-b524-7ea1130c2249)
I see your tool has provided a very good result, but the commands are missing as shown in the image above. For example, I use webshell and type ls -alh, the output will only show /usr/bin/ls and the same with curl, ping, which makes it difficult to investigate. Can I fix it somehow?
Looking forward to hearing from you soon.

**Comment by wagga40** [comment]
I am away right now, I will be able to take a look tomorrow

**Comment by wagga40** [comment]
Hello, it is not easy to work from screenshots, please share your raw logs when you can (even if it is only one event).

Maybe I didn't understand, you have Auditd logs and you are asking why you cannot see your `ls -alh` command ? Since the parameter `-alh` is not appearing in clear text (more on that below) in your Auditd logs, the problem is Auditd related and not really Zircolite related.

So why `--alh` don't appear in clear text ? depending on the way you use Auditd, [the arguments of a command appear hex-encoded](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/security_hardening/auditing-the-system_security-hardening#understanding-audit-log-files_auditing-the-system). For example, in your screenshots the full command can be found in `proctitle=` : 

```shell
$> echo "7368002D63002D2D006578656320323E26313B206C73202D616C68" | xxd -r -p
sh-c--exec 2>&1; ls -alh
```

There are multiple solutions to this : 
- using the Auditd `ausearch` command with the `-i` argument to decode them : `ausearch -if <your log file> -i`
- I could implement something in Zircolite... But It will take time (and I need sample logs...)

As far I can see from your previous issue, the command was perfectly visible in your Sysmon for Linux logs. What you were missing is a Sigma rule to detect it correctly (the closest one is this one [here](https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_webshell_detection.yml))

Lastly, a recommendation : never use the CSV format !!!  😁

**Comment by hoanga2dtk68** [comment]
that's not what i meant, i want to use zircolite as a tool to detect and minimize the need to reread auditd logs, i want zircolite output to show the ls -lah part and not in auditd log. not sure if this is possible

**Comment by wagga40** [comment]
Ok, I reviewed multiple times our discussion... I think I understand now.

The [detection](https://github.com/SigmaHQ/sigma/blob/master/rules/linux/auditd/lnx_auditd_web_rce.yml) occurs on the event `type=SYSCALL msg=audit(1723619808.916:3272): ........` but this event does not contains the full command line which appear in the event just before `type=PROCTITLE msg=audit(1723619808.912:3271): ........`.

Since the [detection](https://github.com/SigmaHQ/sigma/blob/master/rules/linux/auditd/lnx_auditd_web_rce.yml) occurs only on the first event, it is not possible for Zircolite to output in the detected events file an event which did not trigger a rule.

One way to check it, is to keep the flattened events `--keepflat`. But as you said, it would force you to reread some logs.

**Comment by hoanga2dtk68** [comment]
okay, thank you

**Comment by hoanga2dtk68** [comment]
I see that 17236190808.916:3272 then the 3272 part is probably the identifier of an event the events with number 3272 after: when combined together can probably write out the complete command

**Comment by wagga40** [comment]
It won't change anything since the parsing is line-based and not identifier based.
