### ISSUE TITLE
Sqlite vs DuckDb

### ISSUE THREAD

**Issue by MyraBaba** [wagga40/Zircolite#91]
Hi,
@wagga40 
would you consider / possible to use duckDb instead sqlite ? 

for 500MB json :

DuckDB ingestion time: 1.3920 seconds
DuckDB memory usage: 12.11 MB
SQLite ingestion time: 14.3287 seconds
SQLite memory usage: 1105.72 MB

**Comment by wagga40** [comment]
Why not.

The most important thing to understand about Zircolite is that it is based on a [pysigma backend](https://github.com/SigmaHQ/pySigma-backend-sqlite) instead of reimplementing an specific engine. Which mean that if we use something other than SQLite, we may need to create a new backend.

To be honest I did not have a thorough look at DuckDB.

The code is for now quite deeply coupled with SQLite, but feel free to submit some PR with DuckDB support.

**Comment by wagga40** [comment]
Please use discussions instead of issues of you have no bug or problem with Zircolite.
